# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "Android DevFest Season 2014"
email: "organizer@gdgspacecoast.org"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "http://gdg-space-coast.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-41029375-7"
googleAnalyticsSiteUrl: "gdg-space-coast.github.io"

# Organizer Info
organizerName: "GDG Space Coast"
organizerAlternateName: "Google Developer Group Space Coast"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "organizer@gdgspacecoast.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgspacecoast.org/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, developers, Space Coast"
#twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
#socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {link: "https://developers.google.com", text: "Developers"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}

# Hero Block
heroTitle: "Android DevFest <typeout> 2014"
eventDate: "October 18th, 2014"
typeoutTextValues: '"", "Melbourne", "Florida Tech"'
heroButtons:
 - {url: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}

# About Block
aboutTitle: "About Android DevFest"
aboutBlock:
 - {title: "Tech Talks", image: "conference.jpg",
    text: "Come hear the latest updates on Android L, Android TV, Android Wear, Google Glass, and Android Studio." }
 - {title: "Design Sprint", image: "workshop.jpg",
    text: "The design sprint is a process for prototyping and testing any product. This process was just made public by Google Ventures and Google[x] in 2014." }

# Statistic Block
statisticBlock:
 - {count: "110", specialCharacter: "+", info: "attendees", detail: "Developers, Designers, and Business"}
 - {count: "3", specialCharacter: "", info: "hours", detail: "of Android Demos and presentations"}
 - {count: "4", specialCharacter: "+", info: "hours", detail: "of collaboration, brainstorming, and innovation"}
 - {count: "3", specialCharacter: "+", info: "speakers", detail: "experienced in Google technologies"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Florida Institute of Technology"
eventLocationLink: "http://www.fit.edu/"
eventStreetAddress: "150 W University Blvd"
eventAddressLocality: "Melbourne"
eventAddressLocalityRegion: "Florida"
eventPostalCode: "32901"
eventAddressCountry: "USA"
eventStartTime: "2014-10-04T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-04T20:00"
eventPlaceCoordinates: "28.064459,-80.622979"
mapCenterCoordinates: "28.064459,-80.622979"
mapMobileCenterCoordinates: "28.064459,-80.622979"

# Venue Block
venueBlockTitle: "Venue"
venueTitle: "Olin Building"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open in early September. Number of tickets are limited. Stay tuned!"

# Buy Tickets Block
buyTicketsTitle: "Pricetable"
ticketsOffers:
 -
  name: "1 day"
  price: "$10"
  buyButtonLink: "http://gdgspacecoast.org/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Tickets are not on sale yet", "Please check back later", "TBA"]
  validFrom: "2014-10-04T10:00"
  validThrough: "2014-10-04T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://facebook.com/GDGSpace Coast", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgspacecoast.org", text: "GDG Space Coast"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:organizer@gdgspacecoast.org", text: "organizer@gdgspacecoast.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestspacecoast"

# Speakers List Block
showSessions: false
thumbnailsFolder: /img/speakers/

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google Developer Group (GDG) Space Coast is a technology user group that meets to discuss the latest Google Technologies, Tools, SDKs, and APIs. The focus is on learning about the broad spectrum of technologies provided by Google and finding ways that these technologies can be applied. This includes discussions of the technologies from a number of angles (start ups, corporations, and individuals).
<br/><br/>
Here are a few of the topics that we have covered so far:<br/>
Android, Chrome, Chrome OS / Chromium, Google App Engine, Google Play Games Services, GWT, Google Maps for Android, Android Design Guidelines, Dart, AngularJS, Cloud Endpoints, Chrome Packaged Apps, Polymer, Web Components, Ingress, Android Studio, and more.
<br/><br/>
In addition to regular speaker focused meetings, we also organize code camps, hackathons, and assist with the local TrepHub and Startup Weekend events.
<br/><br/>
The group is free to attend and open to all who are interested in discussing and learning more about software development with Google Tools and Technologies.
<br/><br/>
If you would like to stay up to date with events and activities of the group, please follow us on Google+. If you would like to take part in discussions about the group, future events, and future content, please join the GDG Space Coast community linked from our About page on Google+.
<br/><br/>
Disclaimer: GDG Space Coast is an independent group; our activities and the opinions expressed here should in no way be linked to Google, the corporation."

# Logistics Find Way Block
findWayTitle: "Find your way here"
logisticsMapCenterCoordinates: "28.064459,-80.622979"
logisticsMapMobileCenterCoordinates: "28.064459,-80.622979"

# Logistics Direction Details Block
directionDetailsTitle: "Get around the Space Coast"
directionDetailsCards:
 - {title: "From the Airport", information: 'The Melbourne International Airport is just a 10 minute drive (2.5 miles to the south) from Florida Tech. If you need to use the Orlando Airport, then the drive will be 1 hour.'}
 - {title: "Public Transit", information: 'Public transportation in Melbourne is ineffective and difficult to use, especially on weekends. Rental cars from the airport are recommended.'}
 - {title: "Hotels", information: 'Melbourne has many good hotels. There are beachfront hotels with a view or hotels close to the airport for your convenience. See below for more details.'}
directionDetailsWideCards: 
 -
  title: "Details"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.ihg.com/crowneplaza/hotels/us/en/melbourne/mlboc/hoteldetail?cm_mmc=GoogleMaps-_-cp-_-USEN-_-mlboc", text: "Crowne Plaza Melbourne-Oceanfront"}
     - {link: "http://www.doubletreemelbournebeach.com/", text: "DoubleTree Suites by Hilton Melbourne Beach Oceanfront"}
     - {link: "http://www3.hilton.com/en/hotels/florida/hilton-melbourne-rialto-place-MLBMHHF/index.html", text: "Hilton Melbourne Rialto Place"}
     - {link: "http://www.marriott.com/hotels/travel/mlbap-residence-inn-melbourne/", text: "Residence Inn Melbourne"}
   - 
    title: "Travel"
    links:
     - {link: "http://www.mlbair.com/", text: "Melbourne International Airport"}
     - {link: "http://www.orlandoairports.net/", text: "Orlando International Airport"}
     - {link: "http://www.orlandosanfordairport.com/", text: "Orlando Sanford International Airport"}